name: local_notifications_example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  device_info_plus: ^9.0.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.1
  flutter_timezone: ^1.0.7
  http: ^1.1.0
  image: ^4.0.17
  path_provider: ^2.1.1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
